---
- hosts: vagrant

  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.postgresql" }
    - { role: "ckan" }
    - { role: "ckanext-archiver" }
    - { role: "ckanext-disqus" }
    - { role: "ckanext-issues" }
    - { role: "ckanext-spatial" }
    - { role: "ckanext-datajson" }
    - { role: "ckanext-odp_theme" }
    - { role: "ckanext-googleanalytics" }
    - { role: "odp-importer" }
    - { role: "ckan-odp-configuration" }
